ATMSystem/Controllers/ATMController.cs
using ATMSystem.EFDbContext;
using ATMSystem.Models;
using Microsoft.AspNetCore.Mvc;
using IdGen;
using Microsoft.EntityFrameworkCore;

namespace ATMSystem.Controllers
{
    public class ATMController : Controller
    {
        private readonly AppDbContext _appDbContext;
       
        private IdGenerator _idGenerator = new IdGenerator(0);

        public ATMController(AppDbContext appDbContext)
        {
            _appDbContext=appDbContext;
        }

        // Property with a private setter
        public IdGenerator IdGenerator
        {
            get { return _idGenerator; }
            private set { _idGenerator = value; }
        }


        public IActionResult home() 
        { 
            return View();
        }
        [ActionName("signIN")]
        [HttpPost]
        public async Task<IActionResult> SignIn(SignInModel signIn)
        {
            bool logIn = await _appDbContext.Registers.AsNoTracking().AnyAsync(x => x.CardNumber == signIn.CardNumber && x.Password == signIn.Password && x.Active == true);

            if (logIn)
            {
                var userInform = await _appDbContext.Registers.AsNoTracking().FirstOrDefaultAsync(x => x.CardNumber == signIn.CardNumber);
                if (userInform != null)
                {

                    return View("UserAcount", userInform);
                }
                return View();
            }
            else
            {
                return View();
            }

        }
        public IActionResult UserAcount()
        {
            return View();
        }
        public IActionResult create()
        {
            return View();
        }
        [ActionName("Save")]
        [HttpPost]
        public async Task<IActionResult> Registratioin(UserRegisterModel userRegister)
        {
            var number=await _appDbContext.Registers.AsNoTracking().FirstOrDefaultAsync(x=>x.PhoneNumber==userRegister.PhoneNumber);
            if (number!=null)
            {
                return Redirect("create");
            }
            _idGenerator = new IdGenerator(0);
            userRegister.UserID = _idGenerator.CreateId().ToString();
            userRegister.Active = true;
            userRegister.TotalAmount = 0;
            userRegister.CardNumber =Convert.ToInt64( _idGenerator.CreateId().ToString());
            await _appDbContext.Registers.AddAsync(userRegister);
            var result=await _appDbContext.SaveChangesAsync();

            return RedirectToAction("home");
        }


        [HttpPost]
        public async Task<IActionResult> Histroy(string userID)
        {
           
            bool logIn = await _appDbContext.History.AsNoTracking().AnyAsync(x => x.UserID == userID );
            if (logIn)
            {
                List<UserHistoryModel> userHistories = await _appDbContext.History.AsNoTracking().Where(x => x.UserID == userID).OrderByDescending(x => x.LastUpdate).ToListAsync();
               var amount=await _appDbContext.Registers.AsNoTracking().Where(x=>x.UserID== userID).Select(x => new {x.TotalAmount}).FirstOrDefaultAsync();
                var history = new
                {
                    UserHistories = userHistories,
                    Amount = amount
                };
                return Json(history);
            }
            return View();
        }
        public async Task<IActionResult> Nextpage(string userID)
        {
            bool logIn = await _appDbContext.Registers.AsNoTracking().AnyAsync(x => x.UserID == userID && x.Active == true);
            if (logIn)
            {
                var userInform = await _appDbContext.Registers.AsNoTracking().FirstOrDefaultAsync(x => x.UserID == userID && x.Active == true);

                var viewModel = new UserRegisterModel
                {
                    UserID = userInform.UserID,
                };
                return Json("cashOut");
            }
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> CashOut()
        
        {
           
            return View();
        }
        public IActionResult CardLess()
        {
            return View();
        }
        [ActionName("reqeust")]
        [HttpPost]
        public async Task<IActionResult> CashOut(CashOutModel cashOut)
        {
            try
            {
                var withDraw = await _appDbContext.Registers.FirstOrDefaultAsync(x =>x.UserID==cashOut.UserID && x.CardNumber == cashOut.CardNumber && x.PinCode == cashOut.PinCode);
                if (withDraw != null)
                {
                    withDraw.TotalAmount -= cashOut.MoneyAmount;
                    UserHistoryModel history = new UserHistoryModel()
                    {
                        HistoryID = _idGenerator.CreateId().ToString(),
                        UserID = cashOut.UserID,
                        CashOutAmount = cashOut.MoneyAmount,
                        LastUpdate = DateTime.Now
                    };

                    await _appDbContext.History.AddAsync(history);


                }
                var result = await _appDbContext.SaveChangesAsync();

            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }
         
            return View();
        }
       

    }
}

ATMSystem/Views/Shared/_ATM.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sign Up Form by Colorlib</title>
    <!-- Font Icon -->
   
    <!-- Main css -->
    <link rel="stylesheet" href="~/css/style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

</head>
<body>
    <div class="main">
        <!-- Sing in  Form -->
        <section class="sign-in">
            <div class="container">
                <div class="signin-content">
                    @RenderBody()
                </div>
            </div>
        </section>
    </div>
    <!-- JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="~/js/mainScript.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
<!-- This templates was made by Colorlib (https://colorlib.com) -->
</html>

ATMSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ATMSystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ATMSystem.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ATMSystem</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ATM" asp-action="home">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ATMSystem - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ATMSystem/Views/Shared/_Pagination.cshtml
@model PageSettingModel
@{
    int pageNo = Model.PageNo;
    int pageSize = Model.PageSize;
    int pageCount = Model.PageCount;
    string url = Model.PageUrl;
}
<nav aria-label="...">
    <ul class="pagination">
        <li class="page-item @(pageNo == 1 ? "disabled" : "")">
            <a class="page-link" href="@(pageNo == 1  ? "#" : $"{url}?pageNo={pageNo - 1}&pageSize={pageSize}")">Previous</a>
        </li>
        @if (pageCount <= 9)
        {
            @for (int i = 1; i <= pageCount; i++)
            {
                if (pageNo == i)
                {
                    <li class="page-item active" aria-current="page">
                        <a class="page-link" href="#">@i</a>
                    </li>
                }
                else
                {
                    <li class="page-item"><a class="page-link" href="@url?pageNo=@i&pageSize=@pageSize">@i</a></li>
                }
            }
        }
        else
        {
            if (pageNo <= 3 || pageNo >= pageCount - 2)
            {
                @for (int i = 1; i <= 4; i++)
                {
                    if (pageNo == i)
                    {
                        <li class="page-item active" aria-current="page">
                            <a class="page-link" href="#">@i</a>
                        </li>
                    }
                    else
                    {
                        <li class="page-item"><a class="page-link" href="@url?pageNo=@i&pageSize=@pageSize">@i</a></li>
                    }
                }
                <li class="page-item"><a class="page-link" href="#">...</a></li>
                @for (int i = pageCount - 3; i <= pageCount; i++)
                {
                    if (pageNo == i)
                    {
                        <li class="page-item active" aria-current="page">
                            <a class="page-link" href="#">@i</a>
                        </li>
                    }
                    else
                    {
                        <li class="page-item"><a class="page-link" href="@url?pageNo=@i&pageSize=@pageSize">@i</a></li>
                    }
                }
            }
            else
            {
                <li class="page-item"><a class="page-link" href="@url?pageNo=1&pageSize=@pageSize">1</a></li>
                <li class="page-item"><a class="page-link" href="#">...</a></li>
                @for (int i = pageNo - 2; i <= pageNo + 2; i++)
                {
                    if (pageNo == i)
                    {
                        <li class="page-item active" aria-current="page">
                            <a class="page-link" href="#">@i</a>
                        </li>
                    }
                    else
                    {
                        <li class="page-item"><a class="page-link" href="@url?pageNo=@i&pageSize=@pageSize">@i</a></li>
                    }
                }
                <li class="page-item"><a class="page-link" href="#">...</a></li>
                <li class="page-item"><a class="page-link" href="@url?pageNo=@pageCount&pageSize=@pageSize">@pageCount</a></li>
            }
        }
        <li class="page-item @(pageNo == pageCount ? "disabled" : "")">
            <a class="page-link" href="@(pageNo == pageCount  ? "#" : $"{url}?pageNo={pageNo + 1}&pageSize={pageSize}")">Next</a>
        </li>
    </ul>
</nav>